name: jawadrahimi_contact_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  simple_animations: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router: ^14.2.0
  sqflite: ^2.3.0
  path: ^1.9.0
  emoji_picker_flutter: ^4.3.0
  country_flags: ^3.3.0
  google_fonts: ^6.3.1
  lottie: ^3.1.2
  step_progress_indicator: ^1.0.0
  flutter_native_splash: ^2.3.0   # Native splash package
  flutter_launcher_icons: ^0.13.1  # Launcher icon package

flutter:
  uses-material-design: true

  # Assets used in app (and for splash/icon)
  assets:
    - assets/icon/
    - assets/img/


  fonts:
    - family: Poppins
      fonts:

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
      

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/3.png"
  min_sdk_android: 21

# Configuration for flutter_native_splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/4.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFill
  android_12:
    image: assets/icon/4.png
    color: "#ffffff"
